name: aatex_board
description: AATex kanban board.
version: 0.0.3
homepage: https://github.com/awaik/aatex-kanban
repository: https://github.com/awaik/aatex-kanban

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
 

